version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    image: api_frontiers
    # ports:
    #   - "8085:8085"
    volumes:
      - ./data:/data

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: app_frontiers
    ports:
      - "8501:8501"
    volumes:
      - ./data:/data
    depends_on:
      - api

