version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    image: api_frontiers
    volumes:
      - "./data:/app/data"

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: app_frontiers
    ports:
      - "8501:8501"
    depends_on:
      - api

